PUT http://localhost:3003/api/blogs/65ca313778f4edce1fcf4096
Content-Type: application/json

{
    "title": "Hello World!",
    "author": "Test Person",
    "url": "url",
    "likes": 100,
    "userId": "65e83c71e352adc573641099"
}